exclude: 'app/assets/stylesheets/rails_admin/**'

linters:
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: false
  SelectorDepth:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingSemicolon:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  ZeroUnit:
    enabled: false
