application:
  layer: "development"
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
postgres:
  database: calcentral_development
  username: calcentral_development
  password: secret
  host: localhost
  port: 5432
